### ISSUE TITLE
add a guide that shows how to use the error prop

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/status-modal#5]
We just added a new fix to the modal. Formerly if you want to render an error message with status-modal you'll have to use the `status` prop by setting its value to `"error"`. But now, all you need to do alternatively is add an `error` prop alone. 

```jsx
import Status from "status-modal/dist"

const greeting = "Hello HacktoberFest Participant"

return <Status message={greeting} error />
```

Setting the `status` prop to `"error"` still renders an error modal. That gives everyone the freedom to choose whatever prop they feel like using.

What you'll be doing here is adding a new guide in the [README.md](https://github.com/kaf-lamed-beyt/status-modal/#readme), that will show people how to use `status-modal` with the new error prop. You can add the guide below, or in this [section](https://github.com/kaf-lamed-beyt/status-modal/#basic-usage) preferably.  

If you have any questions, please do not hesitate to shoot them. 😎

**Comment by imanpalsingh** [comment]
Hey, what do you mean by guide? Like an example ? or something like

> Alternatively, you can also set the error status with .....

**Comment by kaf-lamed-beyt** [comment]
Yes, something simple like the sentences in the image below. But, if you want to add an example, you can proceed.
![example on how to render error modal style](https://user-images.githubusercontent.com/48127194/193409955-07e399c8-4bb0-4893-b97b-075b3fc09f65.png)

**Comment by imanpalsingh** [comment]
Something like this? https://github.com/kaf-lamed-beyt/status-modal/pull/6 @kaf-lamed-beyt
